#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only

USE_PROCD=1
START=99
STOP=10

PROG="/usr/sbin/onliner"

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    rm -f /tmp/onliner/onliner.lock
}

service_triggers() {
    procd_add_reload_trigger "onliner"
}
